Repository just-a-paw/language, pull requests merged in 2022-01, with the labels that each got.

#4 [Full Audit] Swedish Translations
  sv/commands.json
  sv/core.json
  sv/features.json
  sv/words.json
Labels: translation

#5 refactor(chore): add schemas
  .github/workflows/validate_json.yml
  .vscode/settings.json
  en/commands.json
  en/core.json
  es/commands.json
  es/core.json
  fr/commands.json
  fr/core.json
  locale.schema.json
  schema.json
  sv/core.json
Labels: enhancement

#6 [Edit] Update `sv/commands.json` in Line with PR #5
  sv/commands.json
Labels: refactor

#9 feat: aggregation and tests
  .github/workflows/aggregate.yml
  .gitignore
  .scripts/aggregate.js
  .scripts/test.js
  AGGREGATE.md
  README.md
  azure-pipelines.yml
  index.js
  package-lock.json
  package.json
Labels: feature

#10 refactor: remove global config
  .github/workflows/validate_json.yml
  .vscode/settings.json
  en/locale.json
  es/locale.json
  fr/locale.json
  locale.json
  locale.schema.json
  sv/locale.json
Labels: refactor
